/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_hand (void);
GtkWidget* create_window_bid (void);
GtkWidget* create_window_card (void);
GtkWidget* create_window_bids (void);
