/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_hand (void)
{
  GtkWidget *window_hand;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *neu1;
  GtkWidget *open1;
  GtkWidget *speichern1;
  GtkWidget *speichern_unter1;
  GtkWidget *separatormenuitem1;
  GtkWidget *beenden1;
  GtkWidget *deal1;
  GtkWidget *deal1_menu;
  GtkWidget *deal_clear;
  GtkWidget *deal_random;
  GtkWidget *deal_line;
  GtkWidget *contract1;
  GtkWidget *contract1_menu;
  GSList *declarer_west1_group = NULL;
  GtkWidget *declarer_west1;
  GtkWidget *declarer_north1;
  GtkWidget *declarer_east1;
  GtkWidget *declarer_south1;
  GtkWidget *trennlinie1;
  GSList *contract_no_trump1_group = NULL;
  GtkWidget *contract_no_trump1;
  GtkWidget *contract_spades1;
  GtkWidget *contract_hearts1;
  GtkWidget *contract_diamonds1;
  GtkWidget *contract_clubs1;
  GtkWidget *trennlinie2;
  GtkWidget *level_menu1;
  GtkWidget *level_menu1_menu;
  GSList *level1_group = NULL;
  GtkWidget *level1;
  GtkWidget *level2;
  GtkWidget *level3;
  GtkWidget *level4;
  GtkWidget *level5;
  GtkWidget *level6;
  GtkWidget *level7;
  GtkWidget *level_doubled1;
  GtkWidget *level_redoubled1;
  GtkWidget *vulnerable1;
  GtkWidget *vulnerable1_menu;
  GSList *vuln_none_group = NULL;
  GtkWidget *vuln_none;
  GtkWidget *vuln_ns;
  GtkWidget *vuln_ew;
  GtkWidget *vuln_all;
  GtkWidget *score1;
  GtkWidget *score1_menu;
  GtkWidget *double_dummy1;
  GtkWidget *parscore1;
  GtkWidget *set_par1;
  GtkWidget *positive_for1;
  GtkWidget *positive_for1_menu;
  GSList *pos_north_south_group = NULL;
  GtkWidget *pos_north_south;
  GtkWidget *pos_declarer;
  GtkWidget *pos_current_lead;
  GtkWidget *board_menu1;
  GtkWidget *board_menu1_menu;
  GtkWidget *board1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *ausschneiden1;
  GtkWidget *kopieren1;
  GtkWidget *einf__gen1;
  GtkWidget *l__schen1;
  GtkWidget *menuitem3;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *imp_table1;
  GtkWidget *info1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbutton1;
  GtkWidget *button_hand_save;
  GtkWidget *separatortoolitem2;
  GtkWidget *tmp_image;
  GtkWidget *rewind_button;
  GtkWidget *button_back;
  GtkWidget *button_next;
  GtkWidget *button_fast_forward;
  GtkWidget *separatortoolitem3;
  GtkWidget *handbutton_gib;
  GtkWidget *button_dd;
  GtkWidget *handbutton_par;
  GtkWidget *table1;
  GtkWidget *frame_w;
  GtkWidget *alignment4;
  GtkWidget *table6;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *hbox_west_s;
  GtkWidget *hbox_west_h;
  GtkWidget *hbox_west_d;
  GtkWidget *hbox_west_c;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label_west;
  GtkWidget *frame_e;
  GtkWidget *alignment5;
  GtkWidget *table7;
  GtkWidget *label20;
  GtkWidget *hbox_east_s;
  GtkWidget *hbox_east_h;
  GtkWidget *hbox_east_d;
  GtkWidget *hbox_east_c;
  GtkWidget *label24;
  GtkWidget *label29;
  GtkWidget *label32;
  GtkWidget *label_east;
  GtkWidget *frame_n;
  GtkWidget *alignment6;
  GtkWidget *table_north;
  GtkWidget *label8;
  GtkWidget *hbox_north_s;
  GtkWidget *hbox_north_h;
  GtkWidget *hbox_north_d;
  GtkWidget *hbox_north_c;
  GtkWidget *label26;
  GtkWidget *label30;
  GtkWidget *label34;
  GtkWidget *label_north;
  GtkWidget *frame_s;
  GtkWidget *alignment7;
  GtkWidget *table5;
  GtkWidget *label12;
  GtkWidget *hbox_south_s;
  GtkWidget *hbox_south_h;
  GtkWidget *hbox_south_d;
  GtkWidget *hbox_south_c;
  GtkWidget *label25;
  GtkWidget *label31;
  GtkWidget *label33;
  GtkWidget *label_south;
  GtkWidget *label_tricks;
  GtkWidget *table4;
  GtkWidget *card_south;
  GtkWidget *card_west;
  GtkWidget *card_east;
  GtkWidget *card_north;
  GtkWidget *par_label;
  GtkWidget *label_board;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window_hand = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_hand), _("Tenace"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_hand), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Datei"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  neu1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (neu1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), neu1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  speichern1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (speichern1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), speichern1);

  speichern_unter1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (speichern_unter1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), speichern_unter1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  beenden1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (beenden1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), beenden1);

  deal1 = gtk_menu_item_new_with_mnemonic (_("Deal"));
  gtk_widget_show (deal1);
  gtk_container_add (GTK_CONTAINER (menubar1), deal1);

  deal1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (deal1), deal1_menu);

  deal_clear = gtk_menu_item_new_with_mnemonic (_("Clear"));
  gtk_widget_show (deal_clear);
  gtk_container_add (GTK_CONTAINER (deal1_menu), deal_clear);

  deal_random = gtk_menu_item_new_with_mnemonic (_("Random"));
  gtk_widget_show (deal_random);
  gtk_container_add (GTK_CONTAINER (deal1_menu), deal_random);

  deal_line = gtk_menu_item_new_with_mnemonic (_("Line"));
  gtk_widget_show (deal_line);
  gtk_container_add (GTK_CONTAINER (deal1_menu), deal_line);

  contract1 = gtk_menu_item_new_with_mnemonic (_("Contract"));
  gtk_widget_show (contract1);
  gtk_container_add (GTK_CONTAINER (menubar1), contract1);

  contract1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (contract1), contract1_menu);

  declarer_west1 = gtk_radio_menu_item_new_with_mnemonic (declarer_west1_group, _("West"));
  declarer_west1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (declarer_west1));
  gtk_widget_show (declarer_west1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), declarer_west1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (declarer_west1), TRUE);

  declarer_north1 = gtk_radio_menu_item_new_with_mnemonic (declarer_west1_group, _("North"));
  declarer_west1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (declarer_north1));
  gtk_widget_show (declarer_north1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), declarer_north1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (declarer_north1), TRUE);

  declarer_east1 = gtk_radio_menu_item_new_with_mnemonic (declarer_west1_group, _("East"));
  declarer_west1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (declarer_east1));
  gtk_widget_show (declarer_east1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), declarer_east1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (declarer_east1), TRUE);

  declarer_south1 = gtk_radio_menu_item_new_with_mnemonic (declarer_west1_group, _("South"));
  declarer_west1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (declarer_south1));
  gtk_widget_show (declarer_south1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), declarer_south1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (declarer_south1), TRUE);

  trennlinie1 = gtk_separator_menu_item_new ();
  gtk_widget_show (trennlinie1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), trennlinie1);
  gtk_widget_set_sensitive (trennlinie1, FALSE);

  contract_no_trump1 = gtk_radio_menu_item_new_with_mnemonic (contract_no_trump1_group, _("No Trump"));
  contract_no_trump1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (contract_no_trump1));
  gtk_widget_show (contract_no_trump1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), contract_no_trump1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (contract_no_trump1), TRUE);

  contract_spades1 = gtk_radio_menu_item_new_with_mnemonic (contract_no_trump1_group, _("\342\231\240 Spades"));
  contract_no_trump1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (contract_spades1));
  gtk_widget_show (contract_spades1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), contract_spades1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (contract_spades1), TRUE);

  contract_hearts1 = gtk_radio_menu_item_new_with_mnemonic (contract_no_trump1_group, _("\342\231\245 Hearts"));
  contract_no_trump1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (contract_hearts1));
  gtk_widget_show (contract_hearts1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), contract_hearts1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (contract_hearts1), TRUE);

  contract_diamonds1 = gtk_radio_menu_item_new_with_mnemonic (contract_no_trump1_group, _("\342\231\246 Diamonds"));
  contract_no_trump1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (contract_diamonds1));
  gtk_widget_show (contract_diamonds1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), contract_diamonds1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (contract_diamonds1), TRUE);

  contract_clubs1 = gtk_radio_menu_item_new_with_mnemonic (contract_no_trump1_group, _("\342\231\243 Clubs"));
  contract_no_trump1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (contract_clubs1));
  gtk_widget_show (contract_clubs1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), contract_clubs1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (contract_clubs1), TRUE);

  trennlinie2 = gtk_separator_menu_item_new ();
  gtk_widget_show (trennlinie2);
  gtk_container_add (GTK_CONTAINER (contract1_menu), trennlinie2);
  gtk_widget_set_sensitive (trennlinie2, FALSE);

  level_menu1 = gtk_menu_item_new_with_mnemonic (_("Level"));
  gtk_widget_show (level_menu1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), level_menu1);

  level_menu1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (level_menu1), level_menu1_menu);

  level1 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("1"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level1));
  gtk_widget_show (level1);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level1), TRUE);

  level2 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("2"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level2));
  gtk_widget_show (level2);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level2);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level2), TRUE);

  level3 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("3"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level3));
  gtk_widget_show (level3);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level3);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level3), TRUE);

  level4 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("4"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level4));
  gtk_widget_show (level4);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level4);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level4), TRUE);

  level5 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("5"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level5));
  gtk_widget_show (level5);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level5);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level5), TRUE);

  level6 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("6"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level6));
  gtk_widget_show (level6);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level6);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level6), TRUE);

  level7 = gtk_radio_menu_item_new_with_mnemonic (level1_group, _("7"));
  level1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (level7));
  gtk_widget_show (level7);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level7);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (level7), TRUE);

  level_doubled1 = gtk_check_menu_item_new_with_mnemonic (_("X Doubled"));
  gtk_widget_show (level_doubled1);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level_doubled1);

  level_redoubled1 = gtk_check_menu_item_new_with_mnemonic (_("XX Redoubled"));
  gtk_widget_show (level_redoubled1);
  gtk_container_add (GTK_CONTAINER (level_menu1_menu), level_redoubled1);

  vulnerable1 = gtk_menu_item_new_with_mnemonic (_("Vulnerable"));
  gtk_widget_show (vulnerable1);
  gtk_container_add (GTK_CONTAINER (contract1_menu), vulnerable1);

  vulnerable1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (vulnerable1), vulnerable1_menu);

  vuln_none = gtk_radio_menu_item_new_with_mnemonic (vuln_none_group, _("None"));
  vuln_none_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vuln_none));
  gtk_widget_show (vuln_none);
  gtk_container_add (GTK_CONTAINER (vulnerable1_menu), vuln_none);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (vuln_none), TRUE);

  vuln_ns = gtk_radio_menu_item_new_with_mnemonic (vuln_none_group, _("North-South"));
  vuln_none_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vuln_ns));
  gtk_widget_show (vuln_ns);
  gtk_container_add (GTK_CONTAINER (vulnerable1_menu), vuln_ns);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (vuln_ns), TRUE);

  vuln_ew = gtk_radio_menu_item_new_with_mnemonic (vuln_none_group, _("East-West"));
  vuln_none_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vuln_ew));
  gtk_widget_show (vuln_ew);
  gtk_container_add (GTK_CONTAINER (vulnerable1_menu), vuln_ew);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (vuln_ew), TRUE);

  vuln_all = gtk_radio_menu_item_new_with_mnemonic (vuln_none_group, _("All"));
  vuln_none_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (vuln_all));
  gtk_widget_show (vuln_all);
  gtk_container_add (GTK_CONTAINER (vulnerable1_menu), vuln_all);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (vuln_all), TRUE);

  score1 = gtk_menu_item_new_with_mnemonic (_("Score"));
  gtk_widget_show (score1);
  gtk_container_add (GTK_CONTAINER (menubar1), score1);

  score1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (score1), score1_menu);

  double_dummy1 = gtk_menu_item_new_with_mnemonic (_("Double dummy"));
  gtk_widget_show (double_dummy1);
  gtk_container_add (GTK_CONTAINER (score1_menu), double_dummy1);
  gtk_tooltips_set_tip (tooltips, double_dummy1, _("Double dummy analysis"), NULL);

  parscore1 = gtk_menu_item_new_with_mnemonic (_("Parscore"));
  gtk_widget_show (parscore1);
  gtk_container_add (GTK_CONTAINER (score1_menu), parscore1);
  gtk_tooltips_set_tip (tooltips, parscore1, _("Compute par score and contract"), NULL);

  set_par1 = gtk_menu_item_new_with_mnemonic (_("Play par"));
  gtk_widget_show (set_par1);
  gtk_container_add (GTK_CONTAINER (score1_menu), set_par1);
  gtk_tooltips_set_tip (tooltips, set_par1, _("Set contract to computed par contract"), NULL);

  positive_for1 = gtk_menu_item_new_with_mnemonic (_("Positive for"));
  gtk_widget_show (positive_for1);
  gtk_container_add (GTK_CONTAINER (score1_menu), positive_for1);

  positive_for1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (positive_for1), positive_for1_menu);

  pos_north_south = gtk_radio_menu_item_new_with_mnemonic (pos_north_south_group, _("North-South"));
  pos_north_south_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pos_north_south));
  gtk_widget_show (pos_north_south);
  gtk_container_add (GTK_CONTAINER (positive_for1_menu), pos_north_south);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (pos_north_south), TRUE);

  pos_declarer = gtk_radio_menu_item_new_with_mnemonic (pos_north_south_group, _("Declarer"));
  pos_north_south_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pos_declarer));
  gtk_widget_show (pos_declarer);
  gtk_container_add (GTK_CONTAINER (positive_for1_menu), pos_declarer);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (pos_declarer), TRUE);

  pos_current_lead = gtk_radio_menu_item_new_with_mnemonic (pos_north_south_group, _("Current lead"));
  pos_north_south_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (pos_current_lead));
  gtk_widget_show (pos_current_lead);
  gtk_container_add (GTK_CONTAINER (positive_for1_menu), pos_current_lead);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (pos_current_lead), TRUE);

  board_menu1 = gtk_menu_item_new_with_mnemonic (_("Board"));
  gtk_widget_show (board_menu1);
  gtk_container_add (GTK_CONTAINER (menubar1), board_menu1);

  board_menu1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (board_menu1), board_menu1_menu);

  board1 = gtk_menu_item_new_with_mnemonic (_("Board 1"));
  gtk_widget_show (board1);
  gtk_container_add (GTK_CONTAINER (board_menu1_menu), board1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Bearbeiten"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  ausschneiden1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (ausschneiden1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), ausschneiden1);

  kopieren1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (kopieren1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), kopieren1);

  einf__gen1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (einf__gen1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), einf__gen1);

  l__schen1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (l__schen1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), l__schen1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_Ansicht"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Hilfe"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  imp_table1 = gtk_menu_item_new_with_mnemonic (_("IMP Table"));
  gtk_widget_show (imp_table1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), imp_table1);

  info1 = gtk_menu_item_new_with_mnemonic (_("_Info"));
  gtk_widget_show (info1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), info1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH_HORIZ);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton1 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_show (toolbutton1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton1);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton1), tooltips, _("Open board"), NULL);

  button_hand_save = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_show (button_hand_save);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_hand_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_hand_save), tooltips, _("Save board"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  tmp_image = gtk_image_new_from_stock ("gtk-media-previous", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  rewind_button = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Anfang"));
  gtk_widget_show (rewind_button);
  gtk_container_add (GTK_CONTAINER (toolbar1), rewind_button);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (rewind_button), tooltips, _("Rewind play"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-media-rewind", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_back = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Zur\303\274ck"));
  gtk_widget_show (button_back);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_back);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_back), tooltips, _("Undo card play"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-media-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_next = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Vor"));
  gtk_widget_show (button_next);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_next);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_next), tooltips, _("Play next card"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-media-next", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_fast_forward = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (button_fast_forward);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_fast_forward);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_fast_forward), tooltips, _("Play all cards"), NULL);

  separatortoolitem3 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem3);

  handbutton_gib = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-convert");
  gtk_widget_show (handbutton_gib);
  gtk_container_add (GTK_CONTAINER (toolbar1), handbutton_gib);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (handbutton_gib), tooltips, _("Double dummy analysis"), NULL);

  button_dd = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (button_dd), "");
  tmp_image = gtk_image_new_from_stock ("gtk-convert", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (button_dd), tmp_image);
  gtk_widget_show (button_dd);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_dd);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_dd), tooltips, _("Double dummy analysis"), NULL);

  handbutton_par = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-find");
  gtk_widget_show (handbutton_par);
  gtk_container_add (GTK_CONTAINER (toolbar1), handbutton_par);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (handbutton_par), tooltips, _("Par score"), NULL);

  table1 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  frame_w = gtk_frame_new (NULL);
  gtk_widget_show (frame_w);
  gtk_table_attach (GTK_TABLE (table1), frame_w, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_w), 5);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (frame_w), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 0, 5);

  table6 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (alignment4), table6);

  label16 = gtk_label_new (_("\342\231\240"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table6), label16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label16, -1, 28);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 0);

  label17 = gtk_label_new (_("<span foreground=\"red\">\342\231\245</span>"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table6), label17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label17, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  hbox_west_s = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_west_s);
  gtk_table_attach (GTK_TABLE (table6), hbox_west_s, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_west_h = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_west_h);
  gtk_table_attach (GTK_TABLE (table6), hbox_west_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_west_d = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_west_d);
  gtk_table_attach (GTK_TABLE (table6), hbox_west_d, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_west_c = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_west_c);
  gtk_table_attach (GTK_TABLE (table6), hbox_west_c, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label27 = gtk_label_new (_("<span foreground=\"orange\">\342\231\246</span>"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table6), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label27, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"darkgreen\">\342\231\243</span>"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table6), label28, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label28, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label_west = gtk_label_new (_("West"));
  gtk_widget_show (label_west);
  gtk_frame_set_label_widget (GTK_FRAME (frame_w), label_west);
  gtk_label_set_use_markup (GTK_LABEL (label_west), TRUE);

  frame_e = gtk_frame_new (NULL);
  gtk_widget_show (frame_e);
  gtk_table_attach (GTK_TABLE (table1), frame_e, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_e), 5);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (frame_e), alignment5);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment5), 0, 0, 0, 5);

  table7 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (alignment5), table7);

  label20 = gtk_label_new (_("\342\231\240"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table7), label20, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label20, -1, 28);
  gtk_misc_set_padding (GTK_MISC (label20), 5, 0);

  hbox_east_s = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_east_s);
  gtk_table_attach (GTK_TABLE (table7), hbox_east_s, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_east_h = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_east_h);
  gtk_table_attach (GTK_TABLE (table7), hbox_east_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_east_d = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_east_d);
  gtk_table_attach (GTK_TABLE (table7), hbox_east_d, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_east_c = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_east_c);
  gtk_table_attach (GTK_TABLE (table7), hbox_east_c, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label24 = gtk_label_new (_("<span foreground=\"red\">\342\231\245</span>"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table7), label24, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label24, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label29 = gtk_label_new (_("<span foreground=\"darkgreen\">\342\231\243</span>"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table7), label29, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label29, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label32 = gtk_label_new (_("<span foreground=\"orange\">\342\231\246</span>"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table7), label32, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label32, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label_east = gtk_label_new (_("Ost"));
  gtk_widget_show (label_east);
  gtk_frame_set_label_widget (GTK_FRAME (frame_e), label_east);
  gtk_label_set_use_markup (GTK_LABEL (label_east), TRUE);

  frame_n = gtk_frame_new (NULL);
  gtk_widget_show (frame_n);
  gtk_table_attach (GTK_TABLE (table1), frame_n, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_n), 5);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (frame_n), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 0, 5);

  table_north = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table_north);
  gtk_container_add (GTK_CONTAINER (alignment6), table_north);

  label8 = gtk_label_new (_("\342\231\240"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table_north), label8, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label8, -1, 28);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  hbox_north_s = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_north_s);
  gtk_table_attach (GTK_TABLE (table_north), hbox_north_s, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_north_h = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_north_h);
  gtk_table_attach (GTK_TABLE (table_north), hbox_north_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_north_d = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_north_d);
  gtk_table_attach (GTK_TABLE (table_north), hbox_north_d, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_north_c = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_north_c);
  gtk_table_attach (GTK_TABLE (table_north), hbox_north_c, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label26 = gtk_label_new (_("<span foreground=\"red\">\342\231\245</span>"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table_north), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label26, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label30 = gtk_label_new (_("<span foreground=\"darkgreen\">\342\231\243</span>"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table_north), label30, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label30, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label34 = gtk_label_new (_("<span foreground=\"orange\">\342\231\246</span>"));
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table_north), label34, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label34, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label_north = gtk_label_new (_("Nord"));
  gtk_widget_show (label_north);
  gtk_frame_set_label_widget (GTK_FRAME (frame_n), label_north);
  gtk_label_set_use_markup (GTK_LABEL (label_north), TRUE);

  frame_s = gtk_frame_new (NULL);
  gtk_widget_show (frame_s);
  gtk_table_attach (GTK_TABLE (table1), frame_s, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_s), 5);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame_s), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 0, 5);

  table5 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (alignment7), table5);

  label12 = gtk_label_new (_("\342\231\240"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table5), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label12, -1, 28);
  gtk_misc_set_padding (GTK_MISC (label12), 5, 0);

  hbox_south_s = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_south_s);
  gtk_table_attach (GTK_TABLE (table5), hbox_south_s, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_south_h = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_south_h);
  gtk_table_attach (GTK_TABLE (table5), hbox_south_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_south_d = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_south_d);
  gtk_table_attach (GTK_TABLE (table5), hbox_south_d, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox_south_c = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox_south_c);
  gtk_table_attach (GTK_TABLE (table5), hbox_south_c, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label25 = gtk_label_new (_("<span foreground=\"red\">\342\231\245</span>"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table5), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label25, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label31 = gtk_label_new (_("<span foreground=\"darkgreen\">\342\231\243</span>"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table5), label31, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label31, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label33 = gtk_label_new (_("<span foreground=\"orange\">\342\231\246</span>"));
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table5), label33, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label33, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label_south = gtk_label_new (_("S\303\274d"));
  gtk_widget_show (label_south);
  gtk_frame_set_label_widget (GTK_FRAME (frame_s), label_south);
  gtk_label_set_use_markup (GTK_LABEL (label_south), TRUE);

  label_tricks = gtk_label_new (_("NS: 0\nEW: 0"));
  gtk_widget_show (label_tricks);
  gtk_table_attach (GTK_TABLE (table1), label_tricks, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 5, 0);
  GTK_WIDGET_SET_FLAGS (label_tricks, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (label_tricks), GTK_JUSTIFY_RIGHT);
  gtk_label_set_selectable (GTK_LABEL (label_tricks), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_tricks), 1, 1);

  table4 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table4);
  gtk_table_attach (GTK_TABLE (table1), table4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  card_south = gtk_label_new ("");
  gtk_widget_show (card_south);
  gtk_table_attach (GTK_TABLE (table4), card_south, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  GTK_WIDGET_SET_FLAGS (card_south, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (card_south), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (card_south), TRUE);

  card_west = gtk_label_new ("");
  gtk_widget_show (card_west);
  gtk_table_attach (GTK_TABLE (table4), card_west, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  GTK_WIDGET_SET_FLAGS (card_west, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (card_west), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (card_west), TRUE);
  gtk_misc_set_alignment (GTK_MISC (card_west), 0.49, 0.5);

  card_east = gtk_label_new ("");
  gtk_widget_show (card_east);
  gtk_table_attach (GTK_TABLE (table4), card_east, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  GTK_WIDGET_SET_FLAGS (card_east, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (card_east), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (card_east), TRUE);

  card_north = gtk_label_new ("");
  gtk_widget_show (card_north);
  gtk_table_attach (GTK_TABLE (table4), card_north, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  GTK_WIDGET_SET_FLAGS (card_north, GTK_CAN_FOCUS);
  gtk_label_set_justify (GTK_LABEL (card_north), GTK_JUSTIFY_CENTER);
  gtk_label_set_selectable (GTK_LABEL (card_north), TRUE);

  par_label = gtk_label_new ("");
  gtk_widget_show (par_label);
  gtk_table_attach (GTK_TABLE (table1), par_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 5, 0);
  GTK_WIDGET_SET_FLAGS (par_label, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (par_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (par_label), 0, 1);

  label_board = gtk_label_new (_("Bd 1\n4\342\231\246X S"));
  gtk_widget_show (label_board);
  gtk_table_attach (GTK_TABLE (table1), label_board, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 5, 0);
  GTK_WIDGET_SET_FLAGS (label_board, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (label_board), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_board), 0, 0);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_hand, "delete_event",
                    G_CALLBACK (on_window_hand_delete_event),
                    NULL);
  g_signal_connect ((gpointer) neu1, "activate",
                    G_CALLBACK (on_neu1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) speichern1, "activate",
                    G_CALLBACK (on_speichern1_activate),
                    NULL);
  g_signal_connect ((gpointer) speichern_unter1, "activate",
                    G_CALLBACK (on_speichern_unter1_activate),
                    NULL);
  g_signal_connect ((gpointer) beenden1, "activate",
                    G_CALLBACK (on_beenden1_activate),
                    NULL);
  g_signal_connect ((gpointer) deal_clear, "activate",
                    G_CALLBACK (on_deal_clear_activate),
                    NULL);
  g_signal_connect ((gpointer) deal_random, "activate",
                    G_CALLBACK (on_deal_random_activate),
                    NULL);
  g_signal_connect ((gpointer) deal_line, "activate",
                    G_CALLBACK (on_deal_line_activate),
                    NULL);
  g_signal_connect ((gpointer) declarer_west1, "activate",
                    G_CALLBACK (on_declarer_west1_activate),
                    NULL);
  g_signal_connect ((gpointer) declarer_north1, "activate",
                    G_CALLBACK (on_declarer_north1_activate),
                    NULL);
  g_signal_connect ((gpointer) declarer_east1, "activate",
                    G_CALLBACK (on_declarer_east1_activate),
                    NULL);
  g_signal_connect ((gpointer) declarer_south1, "activate",
                    G_CALLBACK (on_declarer_south1_activate),
                    NULL);
  g_signal_connect ((gpointer) contract_no_trump1, "activate",
                    G_CALLBACK (on_contract_no_trump1_activate),
                    NULL);
  g_signal_connect ((gpointer) contract_spades1, "activate",
                    G_CALLBACK (on_contract_spades1_activate),
                    NULL);
  g_signal_connect ((gpointer) contract_hearts1, "activate",
                    G_CALLBACK (on_contract_hearts1_activate),
                    NULL);
  g_signal_connect ((gpointer) contract_diamonds1, "activate",
                    G_CALLBACK (on_contract_diamonds1_activate),
                    NULL);
  g_signal_connect ((gpointer) contract_clubs1, "activate",
                    G_CALLBACK (on_contract_clubs1_activate),
                    NULL);
  g_signal_connect ((gpointer) level1, "activate",
                    G_CALLBACK (on_level1_activate),
                    NULL);
  g_signal_connect ((gpointer) level2, "activate",
                    G_CALLBACK (on_level2_activate),
                    NULL);
  g_signal_connect ((gpointer) level3, "activate",
                    G_CALLBACK (on_level3_activate),
                    NULL);
  g_signal_connect ((gpointer) level4, "activate",
                    G_CALLBACK (on_level4_activate),
                    NULL);
  g_signal_connect ((gpointer) level5, "activate",
                    G_CALLBACK (on_level5_activate),
                    NULL);
  g_signal_connect ((gpointer) level6, "activate",
                    G_CALLBACK (on_level6_activate),
                    NULL);
  g_signal_connect ((gpointer) level7, "activate",
                    G_CALLBACK (on_level7_activate),
                    NULL);
  g_signal_connect ((gpointer) level_doubled1, "activate",
                    G_CALLBACK (on_level_doubled1_activate),
                    NULL);
  g_signal_connect ((gpointer) level_redoubled1, "activate",
                    G_CALLBACK (on_level_redoubled1_activate),
                    NULL);
  g_signal_connect ((gpointer) vuln_none, "activate",
                    G_CALLBACK (on_vuln_none_activate),
                    NULL);
  g_signal_connect ((gpointer) vuln_ns, "activate",
                    G_CALLBACK (on_vuln_ns_activate),
                    NULL);
  g_signal_connect ((gpointer) vuln_ew, "activate",
                    G_CALLBACK (on_vuln_ew_activate),
                    NULL);
  g_signal_connect ((gpointer) vuln_all, "activate",
                    G_CALLBACK (on_vuln_all_activate),
                    NULL);
  g_signal_connect ((gpointer) double_dummy1, "activate",
                    G_CALLBACK (on_double_dummy1_activate),
                    NULL);
  g_signal_connect ((gpointer) parscore1, "activate",
                    G_CALLBACK (on_parscore1_activate),
                    NULL);
  g_signal_connect ((gpointer) set_par1, "activate",
                    G_CALLBACK (on_set_par1_activate),
                    NULL);
  g_signal_connect ((gpointer) pos_north_south, "activate",
                    G_CALLBACK (on_pos_north_south_activate),
                    NULL);
  g_signal_connect ((gpointer) pos_declarer, "activate",
                    G_CALLBACK (on_pos_declarer_activate),
                    NULL);
  g_signal_connect ((gpointer) pos_current_lead, "activate",
                    G_CALLBACK (on_pos_current_lead_activate),
                    NULL);
  g_signal_connect ((gpointer) board1, "activate",
                    G_CALLBACK (on_board1_activate),
                    NULL);
  g_signal_connect ((gpointer) ausschneiden1, "activate",
                    G_CALLBACK (on_ausschneiden1_activate),
                    NULL);
  g_signal_connect ((gpointer) kopieren1, "activate",
                    G_CALLBACK (on_kopieren1_activate),
                    NULL);
  g_signal_connect ((gpointer) einf__gen1, "activate",
                    G_CALLBACK (on_einf__gen1_activate),
                    NULL);
  g_signal_connect ((gpointer) l__schen1, "activate",
                    G_CALLBACK (on_l__schen1_activate),
                    NULL);
  g_signal_connect ((gpointer) imp_table1, "activate",
                    G_CALLBACK (on_imp_table1_activate),
                    NULL);
  g_signal_connect ((gpointer) info1, "activate",
                    G_CALLBACK (on_info1_activate),
                    NULL);
  g_signal_connect ((gpointer) button_hand_save, "clicked",
                    G_CALLBACK (on_button_hand_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) rewind_button, "clicked",
                    G_CALLBACK (on_rewind_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_back, "clicked",
                    G_CALLBACK (on_button_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_next, "clicked",
                    G_CALLBACK (on_button_next_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_fast_forward, "clicked",
                    G_CALLBACK (on_button_fast_forward_clicked),
                    NULL);
  g_signal_connect ((gpointer) handbutton_gib, "clicked",
                    G_CALLBACK (on_handbutton_gib_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_dd, "toggled",
                    G_CALLBACK (on_button_dd_toggled),
                    NULL);
  g_signal_connect ((gpointer) handbutton_par, "clicked",
                    G_CALLBACK (on_handbutton_par_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_hand, window_hand, "window_hand");
  GLADE_HOOKUP_OBJECT (window_hand, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_hand, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, neu1, "neu1");
  GLADE_HOOKUP_OBJECT (window_hand, open1, "open1");
  GLADE_HOOKUP_OBJECT (window_hand, speichern1, "speichern1");
  GLADE_HOOKUP_OBJECT (window_hand, speichern_unter1, "speichern_unter1");
  GLADE_HOOKUP_OBJECT (window_hand, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (window_hand, beenden1, "beenden1");
  GLADE_HOOKUP_OBJECT (window_hand, deal1, "deal1");
  GLADE_HOOKUP_OBJECT (window_hand, deal1_menu, "deal1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, deal_clear, "deal_clear");
  GLADE_HOOKUP_OBJECT (window_hand, deal_random, "deal_random");
  GLADE_HOOKUP_OBJECT (window_hand, deal_line, "deal_line");
  GLADE_HOOKUP_OBJECT (window_hand, contract1, "contract1");
  GLADE_HOOKUP_OBJECT (window_hand, contract1_menu, "contract1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, declarer_west1, "declarer_west1");
  GLADE_HOOKUP_OBJECT (window_hand, declarer_north1, "declarer_north1");
  GLADE_HOOKUP_OBJECT (window_hand, declarer_east1, "declarer_east1");
  GLADE_HOOKUP_OBJECT (window_hand, declarer_south1, "declarer_south1");
  GLADE_HOOKUP_OBJECT (window_hand, trennlinie1, "trennlinie1");
  GLADE_HOOKUP_OBJECT (window_hand, contract_no_trump1, "contract_no_trump1");
  GLADE_HOOKUP_OBJECT (window_hand, contract_spades1, "contract_spades1");
  GLADE_HOOKUP_OBJECT (window_hand, contract_hearts1, "contract_hearts1");
  GLADE_HOOKUP_OBJECT (window_hand, contract_diamonds1, "contract_diamonds1");
  GLADE_HOOKUP_OBJECT (window_hand, contract_clubs1, "contract_clubs1");
  GLADE_HOOKUP_OBJECT (window_hand, trennlinie2, "trennlinie2");
  GLADE_HOOKUP_OBJECT (window_hand, level_menu1, "level_menu1");
  GLADE_HOOKUP_OBJECT (window_hand, level_menu1_menu, "level_menu1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, level1, "level1");
  GLADE_HOOKUP_OBJECT (window_hand, level2, "level2");
  GLADE_HOOKUP_OBJECT (window_hand, level3, "level3");
  GLADE_HOOKUP_OBJECT (window_hand, level4, "level4");
  GLADE_HOOKUP_OBJECT (window_hand, level5, "level5");
  GLADE_HOOKUP_OBJECT (window_hand, level6, "level6");
  GLADE_HOOKUP_OBJECT (window_hand, level7, "level7");
  GLADE_HOOKUP_OBJECT (window_hand, level_doubled1, "level_doubled1");
  GLADE_HOOKUP_OBJECT (window_hand, level_redoubled1, "level_redoubled1");
  GLADE_HOOKUP_OBJECT (window_hand, vulnerable1, "vulnerable1");
  GLADE_HOOKUP_OBJECT (window_hand, vulnerable1_menu, "vulnerable1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, vuln_none, "vuln_none");
  GLADE_HOOKUP_OBJECT (window_hand, vuln_ns, "vuln_ns");
  GLADE_HOOKUP_OBJECT (window_hand, vuln_ew, "vuln_ew");
  GLADE_HOOKUP_OBJECT (window_hand, vuln_all, "vuln_all");
  GLADE_HOOKUP_OBJECT (window_hand, score1, "score1");
  GLADE_HOOKUP_OBJECT (window_hand, score1_menu, "score1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, double_dummy1, "double_dummy1");
  GLADE_HOOKUP_OBJECT (window_hand, parscore1, "parscore1");
  GLADE_HOOKUP_OBJECT (window_hand, set_par1, "set_par1");
  GLADE_HOOKUP_OBJECT (window_hand, positive_for1, "positive_for1");
  GLADE_HOOKUP_OBJECT (window_hand, positive_for1_menu, "positive_for1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, pos_north_south, "pos_north_south");
  GLADE_HOOKUP_OBJECT (window_hand, pos_declarer, "pos_declarer");
  GLADE_HOOKUP_OBJECT (window_hand, pos_current_lead, "pos_current_lead");
  GLADE_HOOKUP_OBJECT (window_hand, board_menu1, "board_menu1");
  GLADE_HOOKUP_OBJECT (window_hand, board_menu1_menu, "board_menu1_menu");
  GLADE_HOOKUP_OBJECT (window_hand, board1, "board1");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (window_hand, ausschneiden1, "ausschneiden1");
  GLADE_HOOKUP_OBJECT (window_hand, kopieren1, "kopieren1");
  GLADE_HOOKUP_OBJECT (window_hand, einf__gen1, "einf__gen1");
  GLADE_HOOKUP_OBJECT (window_hand, l__schen1, "l__schen1");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window_hand, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window_hand, imp_table1, "imp_table1");
  GLADE_HOOKUP_OBJECT (window_hand, info1, "info1");
  GLADE_HOOKUP_OBJECT (window_hand, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window_hand, toolbutton1, "toolbutton1");
  GLADE_HOOKUP_OBJECT (window_hand, button_hand_save, "button_hand_save");
  GLADE_HOOKUP_OBJECT (window_hand, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (window_hand, rewind_button, "rewind_button");
  GLADE_HOOKUP_OBJECT (window_hand, button_back, "button_back");
  GLADE_HOOKUP_OBJECT (window_hand, button_next, "button_next");
  GLADE_HOOKUP_OBJECT (window_hand, button_fast_forward, "button_fast_forward");
  GLADE_HOOKUP_OBJECT (window_hand, separatortoolitem3, "separatortoolitem3");
  GLADE_HOOKUP_OBJECT (window_hand, handbutton_gib, "handbutton_gib");
  GLADE_HOOKUP_OBJECT (window_hand, button_dd, "button_dd");
  GLADE_HOOKUP_OBJECT (window_hand, handbutton_par, "handbutton_par");
  GLADE_HOOKUP_OBJECT (window_hand, table1, "table1");
  GLADE_HOOKUP_OBJECT (window_hand, frame_w, "frame_w");
  GLADE_HOOKUP_OBJECT (window_hand, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_hand, table6, "table6");
  GLADE_HOOKUP_OBJECT (window_hand, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_hand, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_west_s, "hbox_west_s");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_west_h, "hbox_west_h");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_west_d, "hbox_west_d");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_west_c, "hbox_west_c");
  GLADE_HOOKUP_OBJECT (window_hand, label27, "label27");
  GLADE_HOOKUP_OBJECT (window_hand, label28, "label28");
  GLADE_HOOKUP_OBJECT (window_hand, label_west, "label_west");
  GLADE_HOOKUP_OBJECT (window_hand, frame_e, "frame_e");
  GLADE_HOOKUP_OBJECT (window_hand, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_hand, table7, "table7");
  GLADE_HOOKUP_OBJECT (window_hand, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_east_s, "hbox_east_s");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_east_h, "hbox_east_h");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_east_d, "hbox_east_d");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_east_c, "hbox_east_c");
  GLADE_HOOKUP_OBJECT (window_hand, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_hand, label29, "label29");
  GLADE_HOOKUP_OBJECT (window_hand, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_hand, label_east, "label_east");
  GLADE_HOOKUP_OBJECT (window_hand, frame_n, "frame_n");
  GLADE_HOOKUP_OBJECT (window_hand, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_hand, table_north, "table_north");
  GLADE_HOOKUP_OBJECT (window_hand, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_north_s, "hbox_north_s");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_north_h, "hbox_north_h");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_north_d, "hbox_north_d");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_north_c, "hbox_north_c");
  GLADE_HOOKUP_OBJECT (window_hand, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_hand, label30, "label30");
  GLADE_HOOKUP_OBJECT (window_hand, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_hand, label_north, "label_north");
  GLADE_HOOKUP_OBJECT (window_hand, frame_s, "frame_s");
  GLADE_HOOKUP_OBJECT (window_hand, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_hand, table5, "table5");
  GLADE_HOOKUP_OBJECT (window_hand, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_south_s, "hbox_south_s");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_south_h, "hbox_south_h");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_south_d, "hbox_south_d");
  GLADE_HOOKUP_OBJECT (window_hand, hbox_south_c, "hbox_south_c");
  GLADE_HOOKUP_OBJECT (window_hand, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_hand, label31, "label31");
  GLADE_HOOKUP_OBJECT (window_hand, label33, "label33");
  GLADE_HOOKUP_OBJECT (window_hand, label_south, "label_south");
  GLADE_HOOKUP_OBJECT (window_hand, label_tricks, "label_tricks");
  GLADE_HOOKUP_OBJECT (window_hand, table4, "table4");
  GLADE_HOOKUP_OBJECT (window_hand, card_south, "card_south");
  GLADE_HOOKUP_OBJECT (window_hand, card_west, "card_west");
  GLADE_HOOKUP_OBJECT (window_hand, card_east, "card_east");
  GLADE_HOOKUP_OBJECT (window_hand, card_north, "card_north");
  GLADE_HOOKUP_OBJECT (window_hand, par_label, "par_label");
  GLADE_HOOKUP_OBJECT (window_hand, label_board, "label_board");
  GLADE_HOOKUP_OBJECT (window_hand, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (window_hand, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (window_hand), accel_group);

  return window_hand;
}

GtkWidget*
create_window_bid (void)
{
  GtkWidget *window_bid;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_bid;

  window_bid = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_bid), _("Bidding"));

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (window_bid), scrolledwindow1);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview_bid = gtk_tree_view_new ();
  gtk_widget_show (treeview_bid);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_bid);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_bid, window_bid, "window_bid");
  GLADE_HOOKUP_OBJECT (window_bid, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_bid, treeview_bid, "treeview_bid");

  return window_bid;
}

GtkWidget*
create_window_card (void)
{
  GtkWidget *window_card;
  GtkWidget *vbox2;
  GtkWidget *toolbar2;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton_card_wipe;
  GtkWidget *toolbutton_card_random;
  GtkWidget *separatortoolitem1;
  GSList *radiotoolbutton_west_group = NULL;
  GtkWidget *radiotoolbutton_west;
  GtkWidget *radiotoolbutton_north;
  GtkWidget *radiotoolbutton_east;
  GtkWidget *radiotoolbutton_south;
  GtkWidget *table_cards;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window_card = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_card), _("Cards"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (window_card), vbox2);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_box_pack_start (GTK_BOX (vbox2), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-delete", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton_card_wipe = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbutton_card_wipe);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolbutton_card_wipe);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_card_wipe), tooltips, _("Clear board"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton_card_random = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Zufall"));
  gtk_widget_show (toolbutton_card_random);
  gtk_container_add (GTK_CONTAINER (toolbar2), toolbutton_card_random);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_card_random), tooltips, _("Deal randomly"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar2), separatortoolitem1);

  radiotoolbutton_west = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton_west), _("West"));
  tmp_image = gtk_image_new_from_stock ("gtk-go-back", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton_west), tmp_image);
  gtk_widget_show (radiotoolbutton_west);
  gtk_container_add (GTK_CONTAINER (toolbar2), radiotoolbutton_west);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (radiotoolbutton_west), tooltips, _("West"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_west), radiotoolbutton_west_group);
  radiotoolbutton_west_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_west));

  radiotoolbutton_north = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton_north), _("Nord"));
  tmp_image = gtk_image_new_from_stock ("gtk-go-up", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton_north), tmp_image);
  gtk_widget_show (radiotoolbutton_north);
  gtk_container_add (GTK_CONTAINER (toolbar2), radiotoolbutton_north);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (radiotoolbutton_north), tooltips, _("North"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_north), radiotoolbutton_west_group);
  radiotoolbutton_west_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_north));

  radiotoolbutton_east = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton_east), _("Ost"));
  tmp_image = gtk_image_new_from_stock ("gtk-go-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton_east), tmp_image);
  gtk_widget_show (radiotoolbutton_east);
  gtk_container_add (GTK_CONTAINER (toolbar2), radiotoolbutton_east);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (radiotoolbutton_east), tooltips, _("East"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_east), radiotoolbutton_west_group);
  radiotoolbutton_west_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_east));

  radiotoolbutton_south = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (radiotoolbutton_south), _("S\303\274d"));
  tmp_image = gtk_image_new_from_stock ("gtk-go-down", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (radiotoolbutton_south), tmp_image);
  gtk_widget_show (radiotoolbutton_south);
  gtk_container_add (GTK_CONTAINER (toolbar2), radiotoolbutton_south);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (radiotoolbutton_south), tooltips, _("South"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_south), radiotoolbutton_west_group);
  radiotoolbutton_west_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (radiotoolbutton_south));

  table_cards = gtk_table_new (4, 15, FALSE);
  gtk_widget_show (table_cards);
  gtk_box_pack_start (GTK_BOX (vbox2), table_cards, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("\342\231\240"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table_cards), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK), 0, 0);

  label2 = gtk_label_new (_("<span foreground=\"red\">\342\231\245</span>"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table_cards), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label3 = gtk_label_new (_("<span foreground=\"orange\">\342\231\246</span>"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table_cards), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label4 = gtk_label_new (_("<span foreground=\"darkgreen\">\342\231\243</span>"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table_cards), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  g_signal_connect ((gpointer) toolbutton_card_wipe, "clicked",
                    G_CALLBACK (on_toolbutton_card_wipe_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_card_random, "clicked",
                    G_CALLBACK (on_toolbutton_card_random_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton_west, "clicked",
                    G_CALLBACK (on_radiotoolbutton_west_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton_north, "clicked",
                    G_CALLBACK (on_radiotoolbutton_north_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton_east, "clicked",
                    G_CALLBACK (on_radiotoolbutton_east_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiotoolbutton_south, "clicked",
                    G_CALLBACK (on_radiotoolbutton_south_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_card, window_card, "window_card");
  GLADE_HOOKUP_OBJECT (window_card, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_card, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (window_card, toolbutton_card_wipe, "toolbutton_card_wipe");
  GLADE_HOOKUP_OBJECT (window_card, toolbutton_card_random, "toolbutton_card_random");
  GLADE_HOOKUP_OBJECT (window_card, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (window_card, radiotoolbutton_west, "radiotoolbutton_west");
  GLADE_HOOKUP_OBJECT (window_card, radiotoolbutton_north, "radiotoolbutton_north");
  GLADE_HOOKUP_OBJECT (window_card, radiotoolbutton_east, "radiotoolbutton_east");
  GLADE_HOOKUP_OBJECT (window_card, radiotoolbutton_south, "radiotoolbutton_south");
  GLADE_HOOKUP_OBJECT (window_card, table_cards, "table_cards");
  GLADE_HOOKUP_OBJECT (window_card, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_card, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_card, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_card, label4, "label4");
  GLADE_HOOKUP_OBJECT_NO_REF (window_card, tooltips, "tooltips");

  return window_card;
}

GtkWidget*
create_window_bids (void)
{
  GtkWidget *window_bids;
  GtkWidget *vbox3;
  GtkWidget *toolbar3;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbutton5;
  GtkWidget *hbuttonbox1;
  GtkWidget *bid_pass;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label5;
  GtkWidget *bid_x;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *bid_xx;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *table3;

  window_bids = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_bids), _("Bids"));

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window_bids), vbox3);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (vbox3), toolbar3, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3));

  toolbutton5 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-delete");
  gtk_widget_show (toolbutton5);
  gtk_container_add (GTK_CONTAINER (toolbar3), toolbutton5);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox1, FALSE, TRUE, 0);

  bid_pass = gtk_button_new ();
  gtk_widget_show (bid_pass);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), bid_pass);
  GTK_WIDGET_SET_FLAGS (bid_pass, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (bid_pass), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Pass"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  bid_x = gtk_button_new ();
  gtk_widget_show (bid_x);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), bid_x);
  GTK_WIDGET_SET_FLAGS (bid_x, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (bid_x), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("X"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  bid_xx = gtk_button_new ();
  gtk_widget_show (bid_xx);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), bid_xx);
  GTK_WIDGET_SET_FLAGS (bid_xx, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (bid_xx), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("XX"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  table3 = gtk_table_new (7, 4, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox3), table3, TRUE, TRUE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_bids, window_bids, "window_bids");
  GLADE_HOOKUP_OBJECT (window_bids, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window_bids, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (window_bids, toolbutton5, "toolbutton5");
  GLADE_HOOKUP_OBJECT (window_bids, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_bids, bid_pass, "bid_pass");
  GLADE_HOOKUP_OBJECT (window_bids, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_bids, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_bids, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_bids, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_bids, bid_x, "bid_x");
  GLADE_HOOKUP_OBJECT (window_bids, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_bids, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_bids, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_bids, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_bids, bid_xx, "bid_xx");
  GLADE_HOOKUP_OBJECT (window_bids, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_bids, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_bids, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_bids, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_bids, table3, "table3");

  return window_bids;
}

GtkWidget*
create_window_imps (void)
{
  GtkWidget *window_imps;
  GtkWidget *vbox4;
  GtkWidget *table8;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label50;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *label49;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox2;
  GtkWidget *imps_ok;

  window_imps = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_imps), _("IMP Table"));

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (window_imps), vbox4);

  table8 = gtk_table_new (12, 4, FALSE);
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (vbox4), table8, FALSE, FALSE, 0);

  label36 = gtk_label_new ("0-10");
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table8), label36, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0.49, 0.42);

  label37 = gtk_label_new ("0");
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table8), label37, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label38 = gtk_label_new ("20-40");
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table8), label38, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label39 = gtk_label_new ("1");
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table8), label39, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label40 = gtk_label_new ("2");
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table8), label40, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label41 = gtk_label_new ("3");
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table8), label41, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label42 = gtk_label_new ("4");
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table8), label42, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label43 = gtk_label_new ("5");
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table8), label43, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label44 = gtk_label_new ("6");
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table8), label44, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label45 = gtk_label_new ("7");
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table8), label45, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label46 = gtk_label_new ("8");
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table8), label46, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label47 = gtk_label_new ("9");
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table8), label47, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label48 = gtk_label_new ("10");
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table8), label48, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label51 = gtk_label_new ("50-80");
  gtk_widget_show (label51);
  gtk_table_attach (GTK_TABLE (table8), label51, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label52 = gtk_label_new ("90-120");
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table8), label52, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label53 = gtk_label_new ("130-160");
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table8), label53, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label61 = gtk_label_new ("170-210");
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table8), label61, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label62 = gtk_label_new ("220-260");
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table8), label62, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label63 = gtk_label_new ("270-310");
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table8), label63, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label64 = gtk_label_new ("320-360");
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table8), label64, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label65 = gtk_label_new ("370-420");
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table8), label65, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label66 = gtk_label_new ("430-490");
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table8), label66, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label67 = gtk_label_new ("500-590");
  gtk_widget_show (label67);
  gtk_table_attach (GTK_TABLE (table8), label67, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label67), 5, 0);

  label50 = gtk_label_new ("12");
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table8), label50, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label69 = gtk_label_new ("3500-3990");
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table8), label69, 2, 3, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label69), 5, 0);

  label70 = gtk_label_new ("600-740");
  gtk_widget_show (label70);
  gtk_table_attach (GTK_TABLE (table8), label70, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label70), 0.49, 0.5);

  label71 = gtk_label_new ("750-890");
  gtk_widget_show (label71);
  gtk_table_attach (GTK_TABLE (table8), label71, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label71), 0.49, 0.5);

  label72 = gtk_label_new ("900-1090");
  gtk_widget_show (label72);
  gtk_table_attach (GTK_TABLE (table8), label72, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label72), 0.49, 0.5);

  label73 = gtk_label_new ("1100-1290");
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table8), label73, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label73), 0.49, 0.5);

  label74 = gtk_label_new ("1300-1490");
  gtk_widget_show (label74);
  gtk_table_attach (GTK_TABLE (table8), label74, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label74), 0.49, 0.5);

  label75 = gtk_label_new ("1500-1740");
  gtk_widget_show (label75);
  gtk_table_attach (GTK_TABLE (table8), label75, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label75), 0.49, 0.5);

  label76 = gtk_label_new ("1750-1990");
  gtk_widget_show (label76);
  gtk_table_attach (GTK_TABLE (table8), label76, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label76), 0.49, 0.5);

  label77 = gtk_label_new ("2000-2240");
  gtk_widget_show (label77);
  gtk_table_attach (GTK_TABLE (table8), label77, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label77), 0.49, 0.5);

  label78 = gtk_label_new ("2250-2490");
  gtk_widget_show (label78);
  gtk_table_attach (GTK_TABLE (table8), label78, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label78), 0.49, 0.5);

  label79 = gtk_label_new ("2500-2990");
  gtk_widget_show (label79);
  gtk_table_attach (GTK_TABLE (table8), label79, 2, 3, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label79), 0.49, 0.5);

  label80 = gtk_label_new ("3000-3490");
  gtk_widget_show (label80);
  gtk_table_attach (GTK_TABLE (table8), label80, 2, 3, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label80), 0.49, 0.5);

  label81 = gtk_label_new ("13");
  gtk_widget_show (label81);
  gtk_table_attach (GTK_TABLE (table8), label81, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label82 = gtk_label_new ("14");
  gtk_widget_show (label82);
  gtk_table_attach (GTK_TABLE (table8), label82, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label83 = gtk_label_new ("15");
  gtk_widget_show (label83);
  gtk_table_attach (GTK_TABLE (table8), label83, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label84 = gtk_label_new ("16");
  gtk_widget_show (label84);
  gtk_table_attach (GTK_TABLE (table8), label84, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label85 = gtk_label_new ("17");
  gtk_widget_show (label85);
  gtk_table_attach (GTK_TABLE (table8), label85, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label86 = gtk_label_new ("18");
  gtk_widget_show (label86);
  gtk_table_attach (GTK_TABLE (table8), label86, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label87 = gtk_label_new ("19");
  gtk_widget_show (label87);
  gtk_table_attach (GTK_TABLE (table8), label87, 3, 4, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label88 = gtk_label_new ("20");
  gtk_widget_show (label88);
  gtk_table_attach (GTK_TABLE (table8), label88, 3, 4, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label89 = gtk_label_new ("21");
  gtk_widget_show (label89);
  gtk_table_attach (GTK_TABLE (table8), label89, 3, 4, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label90 = gtk_label_new ("22");
  gtk_widget_show (label90);
  gtk_table_attach (GTK_TABLE (table8), label90, 3, 4, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label91 = gtk_label_new ("23");
  gtk_widget_show (label91);
  gtk_table_attach (GTK_TABLE (table8), label91, 3, 4, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label91), 5, 0);

  label49 = gtk_label_new ("11");
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table8), label49, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label49), 5, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator1, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox2, FALSE, FALSE, 5);

  imps_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (imps_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), imps_ok);
  GTK_WIDGET_SET_FLAGS (imps_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window_imps, "delete_event",
                    G_CALLBACK (on_window_imps_delete_event),
                    NULL);
  g_signal_connect ((gpointer) window_imps, "destroy_event",
                    G_CALLBACK (on_window_imps_delete_event),
                    NULL);
  g_signal_connect ((gpointer) imps_ok, "clicked",
                    G_CALLBACK (on_imps_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_imps, window_imps, "window_imps");
  GLADE_HOOKUP_OBJECT (window_imps, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window_imps, table8, "table8");
  GLADE_HOOKUP_OBJECT (window_imps, label36, "label36");
  GLADE_HOOKUP_OBJECT (window_imps, label37, "label37");
  GLADE_HOOKUP_OBJECT (window_imps, label38, "label38");
  GLADE_HOOKUP_OBJECT (window_imps, label39, "label39");
  GLADE_HOOKUP_OBJECT (window_imps, label40, "label40");
  GLADE_HOOKUP_OBJECT (window_imps, label41, "label41");
  GLADE_HOOKUP_OBJECT (window_imps, label42, "label42");
  GLADE_HOOKUP_OBJECT (window_imps, label43, "label43");
  GLADE_HOOKUP_OBJECT (window_imps, label44, "label44");
  GLADE_HOOKUP_OBJECT (window_imps, label45, "label45");
  GLADE_HOOKUP_OBJECT (window_imps, label46, "label46");
  GLADE_HOOKUP_OBJECT (window_imps, label47, "label47");
  GLADE_HOOKUP_OBJECT (window_imps, label48, "label48");
  GLADE_HOOKUP_OBJECT (window_imps, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_imps, label52, "label52");
  GLADE_HOOKUP_OBJECT (window_imps, label53, "label53");
  GLADE_HOOKUP_OBJECT (window_imps, label61, "label61");
  GLADE_HOOKUP_OBJECT (window_imps, label62, "label62");
  GLADE_HOOKUP_OBJECT (window_imps, label63, "label63");
  GLADE_HOOKUP_OBJECT (window_imps, label64, "label64");
  GLADE_HOOKUP_OBJECT (window_imps, label65, "label65");
  GLADE_HOOKUP_OBJECT (window_imps, label66, "label66");
  GLADE_HOOKUP_OBJECT (window_imps, label67, "label67");
  GLADE_HOOKUP_OBJECT (window_imps, label50, "label50");
  GLADE_HOOKUP_OBJECT (window_imps, label69, "label69");
  GLADE_HOOKUP_OBJECT (window_imps, label70, "label70");
  GLADE_HOOKUP_OBJECT (window_imps, label71, "label71");
  GLADE_HOOKUP_OBJECT (window_imps, label72, "label72");
  GLADE_HOOKUP_OBJECT (window_imps, label73, "label73");
  GLADE_HOOKUP_OBJECT (window_imps, label74, "label74");
  GLADE_HOOKUP_OBJECT (window_imps, label75, "label75");
  GLADE_HOOKUP_OBJECT (window_imps, label76, "label76");
  GLADE_HOOKUP_OBJECT (window_imps, label77, "label77");
  GLADE_HOOKUP_OBJECT (window_imps, label78, "label78");
  GLADE_HOOKUP_OBJECT (window_imps, label79, "label79");
  GLADE_HOOKUP_OBJECT (window_imps, label80, "label80");
  GLADE_HOOKUP_OBJECT (window_imps, label81, "label81");
  GLADE_HOOKUP_OBJECT (window_imps, label82, "label82");
  GLADE_HOOKUP_OBJECT (window_imps, label83, "label83");
  GLADE_HOOKUP_OBJECT (window_imps, label84, "label84");
  GLADE_HOOKUP_OBJECT (window_imps, label85, "label85");
  GLADE_HOOKUP_OBJECT (window_imps, label86, "label86");
  GLADE_HOOKUP_OBJECT (window_imps, label87, "label87");
  GLADE_HOOKUP_OBJECT (window_imps, label88, "label88");
  GLADE_HOOKUP_OBJECT (window_imps, label89, "label89");
  GLADE_HOOKUP_OBJECT (window_imps, label90, "label90");
  GLADE_HOOKUP_OBJECT (window_imps, label91, "label91");
  GLADE_HOOKUP_OBJECT (window_imps, label49, "label49");
  GLADE_HOOKUP_OBJECT (window_imps, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window_imps, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window_imps, imps_ok, "imps_ok");

  return window_imps;
}

GtkWidget*
create_window_info (void)
{
  GtkWidget *window_info;
  GtkWidget *vbox5;
  GtkWidget *label92;
  GtkWidget *hbuttonbox3;
  GtkWidget *info_ok;

  window_info = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_info), _("Info"));

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (window_info), vbox5);

  label92 = gtk_label_new (_("<b>bridgehand</b>\n\n(C) 2007 Christoph Berg &lt;cb@df7cb.de&gt;"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (vbox5), label92, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label92), TRUE);
  gtk_label_set_justify (GTK_LABEL (label92), GTK_JUSTIFY_CENTER);
  gtk_misc_set_padding (GTK_MISC (label92), 5, 0);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox3, TRUE, TRUE, 5);

  info_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (info_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), info_ok);
  GTK_WIDGET_SET_FLAGS (info_ok, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window_info, "delete_event",
                    G_CALLBACK (on_window_info_delete_event),
                    NULL);
  g_signal_connect ((gpointer) window_info, "destroy_event",
                    G_CALLBACK (on_window_info_delete_event),
                    NULL);
  g_signal_connect ((gpointer) info_ok, "clicked",
                    G_CALLBACK (on_info_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_info, window_info, "window_info");
  GLADE_HOOKUP_OBJECT (window_info, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window_info, label92, "label92");
  GLADE_HOOKUP_OBJECT (window_info, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (window_info, info_ok, "info_ok");

  return window_info;
}

GtkWidget*
create_window_line_entry (void)
{
  GtkWidget *window_line_entry;
  GtkWidget *hbox4;
  GtkWidget *line_entry;
  GtkWidget *line_entry_ok;

  window_line_entry = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_line_entry), _("Hand Line"));
  gtk_window_set_default_size (GTK_WINDOW (window_line_entry), 580, -1);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (window_line_entry), hbox4);

  line_entry = gtk_entry_new ();
  gtk_widget_show (line_entry);
  gtk_box_pack_start (GTK_BOX (hbox4), line_entry, TRUE, TRUE, 0);
  gtk_entry_set_text (GTK_ENTRY (line_entry), _("63.A84.K853.KQ72 JT.QJT952.QJT62. Q9854.763.A7.A64 AK72.K.94.JT9853"));

  line_entry_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (line_entry_ok);
  gtk_box_pack_start (GTK_BOX (hbox4), line_entry_ok, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_line_entry, "delete_event",
                    G_CALLBACK (on_window_line_entry_delete_event),
                    NULL);
  g_signal_connect ((gpointer) window_line_entry, "destroy_event",
                    G_CALLBACK (on_window_line_entry_delete_event),
                    NULL);
  g_signal_connect ((gpointer) line_entry, "activate",
                    G_CALLBACK (on_line_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) line_entry_ok, "clicked",
                    G_CALLBACK (on_line_entry_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_line_entry, window_line_entry, "window_line_entry");
  GLADE_HOOKUP_OBJECT (window_line_entry, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_line_entry, line_entry, "line_entry");
  GLADE_HOOKUP_OBJECT (window_line_entry, line_entry_ok, "line_entry_ok");

  return window_line_entry;
}

GtkWidget*
create_window_play (void)
{
  GtkWidget *window_play;
  GtkWidget *vbox6;
  GtkWidget *play_table;

  window_play = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_play), _("Play"));
  gtk_window_set_default_size (GTK_WINDOW (window_play), 150, -1);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (window_play), vbox6);

  play_table = gtk_table_new (13, 5, TRUE);
  gtk_widget_show (play_table);
  gtk_box_pack_start (GTK_BOX (vbox6), play_table, TRUE, TRUE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_play, window_play, "window_play");
  GLADE_HOOKUP_OBJECT (window_play, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (window_play, play_table, "play_table");

  return window_play;
}

