/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_hand (void);
GtkWidget* create_window_card (void);
GtkWidget* create_window_bids (void);
GtkWidget* create_window_imps (void);
GtkWidget* create_window_line_entry (void);
GtkWidget* create_window_play (void);
GtkWidget* create_window_options (void);
GtkWidget* create_aboutdialog1 (void);
